
add_newline = true
format = """
[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold blue)
[â”‚](bold blue) $username $directory $git_branch $git_commit $git_status $nodejs $time
[â””â”€>](bold blue)\
"""
scan_timeout = 10
[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

# Disable the package module, hiding it from the prompt completely: not sure what this does, true/false, behaves the same
[package]
disabled = true

[username]
format = "[$user](bold dimmed)[ @](blue)"
disabled = false
show_always = true

[directory]
style = "italic bg:#282C34 fg:#EEEEEE"
read_only = "ğŸ”’"
read_only_style = "bg:#FF0000 fg:#333333"
truncation_length = 4
truncate_to_repo = true
truncation_symbol = " â€¦/"
home_symbol = "~"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "on [$symbol$branch]($style) "
symbol = "î‚  "
style = "bold purple"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
commit_hash_length = 4
tag_symbol = "ğŸ”– "
style = "bold white"

[git_status]
conflicted = "âš”ï¸ "
ahead      = " â«Ã—${count}"
behind     = " â¬Ã—${count}"
diverged   = " ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked  = " â“Ã—${count}"
stashed    = " ğŸ“¦ "
modified   = " ğŸ“Ã—${count}"
staged     = " ğŸ—ƒï¸ Ã—${count}"
renamed    = " ğŸ“› Ã—${count}"
deleted    = " ğŸ—‘ï¸ Ã—${count}"
style      = "bright-white"
format     = "$all_status$ahead_behind"

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[time]
disabled = false
format = '[\[$time\]]($style) '
